//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TankService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class act
    {
        public System.Guid id { get; set; }
        public int unitid { get; set; }
        public System.DateTime dt { get; set; }
        public System.DateTime dtwrite { get; set; }
        public Nullable<int> shift { get; set; }
        public string number { get; set; }
        public string qpnumber { get; set; }
        public Nullable<double> vol { get; set; }
        public Nullable<double> volstart { get; set; }
        public Nullable<double> volend { get; set; }
        public Nullable<double> mas { get; set; }
        public Nullable<double> masstart { get; set; }
        public Nullable<double> masend { get; set; }
        public Nullable<double> t { get; set; }
        public Nullable<double> pres { get; set; }
        public Nullable<double> dens { get; set; }
        public Nullable<double> dens20 { get; set; }
        public Nullable<double> masnetto { get; set; }
        public Nullable<double> masballast { get; set; }
        public Nullable<double> maslosses { get; set; }
        public Nullable<double> masborder { get; set; }
        public string dtsample { get; set; }
    }
}
