//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TankService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class act_syn
    {
        public System.Guid ID_AS { get; set; }
        public Nullable<System.Guid> ID_AsGroup { get; set; }
        public Nullable<System.Guid> ID_SiknAct { get; set; }
        public Nullable<System.Guid> ID_RO { get; set; }
        public Nullable<System.Guid> ID_QUE { get; set; }
        public Nullable<System.Guid> ID_QP { get; set; }
        public Nullable<int> RepID { get; set; }
        public Nullable<System.DateTime> ActDate { get; set; }
        public Nullable<System.DateTime> QueDate { get; set; }
        public string ActNum { get; set; }
        public string GroupActNum { get; set; }
        public Nullable<double> VolBrutto { get; set; }
        public Nullable<double> MasBrutto { get; set; }
        public Nullable<double> MasBlst { get; set; }
        public Nullable<double> MasNettoSikn { get; set; }
        public Nullable<double> MasOutage { get; set; }
        public Nullable<double> MasNetto { get; set; }
        public Nullable<double> MasNettoClear { get; set; }
        public Nullable<double> MasNetto106 { get; set; }
        public Nullable<double> VolStart { get; set; }
        public Nullable<double> VolEnd { get; set; }
        public Nullable<double> MasStart { get; set; }
        public Nullable<double> MasEnd { get; set; }
        public Nullable<double> OLevelStart { get; set; }
        public Nullable<double> OLevelEnd { get; set; }
        public Nullable<double> WLevelStart { get; set; }
        public Nullable<double> WLevelEnd { get; set; }
        public Nullable<System.DateTime> DrawTime { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
        public Nullable<int> Shift { get; set; }
        public string RoName { get; set; }
        public Nullable<int> TankID { get; set; }
        public string ConsumerName { get; set; }
        public string OriginName { get; set; }
        public string UserName { get; set; }
        public Nullable<bool> lcontrol { get; set; }
        public Nullable<bool> ltransfer { get; set; }
        public Nullable<double> MasBruttoBound { get; set; }
        public Nullable<bool> lprizn_transp { get; set; }
        public Nullable<int> indexInGroup { get; set; }
        public Nullable<bool> mprizn { get; set; }
        public Nullable<double> mpart { get; set; }
        public Nullable<bool> GroupClosed { get; set; }
        public Nullable<double> mpclear { get; set; }
        public Nullable<double> mpbound { get; set; }
        public Nullable<double> mp106 { get; set; }
        public Nullable<double> mpsikn { get; set; }
        public Nullable<double> mppart { get; set; }
        public Nullable<double> mpmasclear { get; set; }
        public Nullable<double> mpmasbound { get; set; }
        public Nullable<double> mpmassikn { get; set; }
        public Nullable<double> mpmasbrutto { get; set; }
        public Nullable<double> mpmasvolume { get; set; }
        public Nullable<double> mpmas106 { get; set; }
        public Nullable<double> mvpart { get; set; }
    }
}
