//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TankService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionLog2
    {
        public int id { get; set; }
        public string username { get; set; }
        public System.DateTime date { get; set; }
        public string operation { get; set; }
        public Nullable<System.Guid> protocolid { get; set; }
        public string remoteip { get; set; }
    }
}
