//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TankService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class calibrationARCHIV
    {
        public int id { get; set; }
        public int tankid { get; set; }
        public int oillevel { get; set; }
        public double oilvolume { get; set; }
        public Nullable<int> filialid { get; set; }
        public Nullable<System.DateTime> DateActual { get; set; }
    }
}
