//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TankService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Correct
    {
        public int id { get; set; }
        public Nullable<int> filial { get; set; }
        public Nullable<int> tankid { get; set; }
        public Nullable<decimal> Uroven { get; set; }
        public Nullable<decimal> Temp { get; set; }
    }
}
