//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TankService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonnyOstat
    {
        public int ID { get; set; }
        public Nullable<int> TankID { get; set; }
        public Nullable<decimal> UrovH2O { get; set; }
        public string Primechanie { get; set; }
        public string UserMod { get; set; }
        public Nullable<System.DateTime> DateMod { get; set; }
        public Nullable<decimal> Zapas { get; set; }
        public Nullable<int> Filial { get; set; }
    }
}
