//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TankService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LastMechanResultMoz
    {
        public Nullable<System.DateTime> endsampledt { get; set; }
        public int tankid { get; set; }
        public Nullable<double> mechan { get; set; }
    }
}
