//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TankService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManualData_old
    {
        public int id { get; set; }
        public int dirId { get; set; }
        public int userId { get; set; }
        public System.DateTime dtwrite { get; set; }
        public System.DateTime dtupdate { get; set; }
        public System.DateTime dt { get; set; }
        public Nullable<double> temperature { get; set; }
        public Nullable<double> density { get; set; }
        public Nullable<double> density20 { get; set; }
        public Nullable<double> water { get; set; }
        public Nullable<double> saltmg { get; set; }
        public Nullable<double> saltprc { get; set; }
        public Nullable<double> mechan { get; set; }
        public Nullable<double> sulphur { get; set; }
        public Nullable<double> hydrogen { get; set; }
        public Nullable<double> mercaptan { get; set; }
        public Nullable<double> organic { get; set; }
        public Nullable<double> visc { get; set; }
    
        public virtual Directions Directions { get; set; }
        public virtual Directions Directions1 { get; set; }
        public virtual Directions Directions2 { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
        public virtual Users Users2 { get; set; }
    }
}
