//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TankService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class oper
    {
        public Nullable<System.Guid> id { get; set; }
        public short type { get; set; }
        public int unitid { get; set; }
        public System.DateTime dt { get; set; }
        public System.DateTime dtwrite { get; set; }
        public int line { get; set; }
        public Nullable<double> volhour { get; set; }
        public Nullable<double> voltotal { get; set; }
        public Nullable<double> mashour { get; set; }
        public Nullable<double> mastotal { get; set; }
        public Nullable<double> t { get; set; }
        public Nullable<double> pres { get; set; }
        public Nullable<double> dens { get; set; }
        public Nullable<double> dens20 { get; set; }
        public Nullable<double> dens15 { get; set; }
        public Nullable<double> tbik { get; set; }
        public Nullable<double> presbik { get; set; }
        public Nullable<double> vol20 { get; set; }
        public Nullable<double> vol15 { get; set; }
        public Nullable<double> visc { get; set; }
    }
}
