//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TankService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Passport
    {
        public System.Guid id { get; set; }
        public int filialid { get; set; }
        public int num { get; set; }
        public int shift { get; set; }
        public System.DateTime dt { get; set; }
        public System.DateTime dtsample { get; set; }
        public Nullable<System.DateTime> dtsamplelast { get; set; }
        public Nullable<System.DateTime> dtclose { get; set; }
        public string closelevel { get; set; }
        public int samplesourceid { get; set; }
        public int samplelocationid { get; set; }
        public int laborantid { get; set; }
        public int operatorid { get; set; }
        public int recipientid { get; set; }
        public bool throughsikn { get; set; }
        public Nullable<int> throughsiknid { get; set; }
        public Nullable<double> tempreal { get; set; }
        public Nullable<double> pressure { get; set; }
        public Nullable<double> densreal { get; set; }
        public Nullable<double> dens20 { get; set; }
        public Nullable<double> dens15 { get; set; }
        public Nullable<double> water { get; set; }
        public Nullable<double> saltmg { get; set; }
        public Nullable<double> salt { get; set; }
        public Nullable<double> mechan { get; set; }
        public Nullable<double> sulphur { get; set; }
        public Nullable<double> vaporpres { get; set; }
        public Nullable<double> fr200 { get; set; }
        public Nullable<double> fr300 { get; set; }
        public Nullable<double> paraffin { get; set; }
        public Nullable<double> hydrogen { get; set; }
        public Nullable<double> mercaptan { get; set; }
        public Nullable<double> organic { get; set; }
        public Nullable<double> visc { get; set; }
        public string designation { get; set; }
    }
}
