//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TankService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person2
    {
        public int id { get; set; }
        public int filialid { get; set; }
        public string name { get; set; }
        public string position { get; set; }
        public Nullable<short> rank { get; set; }
        public int departmentid { get; set; }
        public bool chief { get; set; }
        public bool approve { get; set; }
        public bool enable { get; set; }
    }
}
