//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TankService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Person()
        {
            this.Users2old = new HashSet<Users2old>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int filialid { get; set; }
        public string position { get; set; }
        public int departmentid { get; set; }
        public bool approve { get; set; }
        public Nullable<short> rank { get; set; }
        public Nullable<bool> enable { get; set; }
        public bool chief { get; set; }
        public string surname { get; set; }
        public string patronymic { get; set; }
        public string name1 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Users2old> Users2old { get; set; }
    }
}
