//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TankService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProtocolRoom_old
    {
        public int id { get; set; }
        public System.Guid protocolid { get; set; }
        public int roomid { get; set; }
        public string temperature { get; set; }
        public string pressure { get; set; }
        public string humidity { get; set; }
        public string uid { get; set; }
    }
}
