//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TankService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProtocolResult_trash
    {
        public Nullable<System.DateTime> logdate { get; set; }
        public int id { get; set; }
        public System.Guid protocolid { get; set; }
        public Nullable<double> tempareom { get; set; }
        public Nullable<double> tempreal { get; set; }
        public Nullable<double> densareom { get; set; }
        public Nullable<double> densreal { get; set; }
        public Nullable<double> dens20 { get; set; }
        public Nullable<double> dens15 { get; set; }
        public Nullable<double> water { get; set; }
        public Nullable<double> saltmg { get; set; }
        public Nullable<double> mechan { get; set; }
        public Nullable<double> sulphur { get; set; }
        public Nullable<double> vaporpres { get; set; }
        public Nullable<double> fr200 { get; set; }
        public Nullable<double> fr300 { get; set; }
        public Nullable<double> fr350 { get; set; }
        public Nullable<double> paraffin { get; set; }
        public Nullable<double> hydrogen { get; set; }
        public Nullable<double> mercaptan { get; set; }
        public Nullable<double> organic { get; set; }
        public Nullable<double> visc { get; set; }
        public Nullable<double> pressure { get; set; }
        public Nullable<double> ethylmercaptan { get; set; }
        public Nullable<double> methylmercaptan { get; set; }
        public Nullable<double> densAstm { get; set; }
    }
}
