//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TankService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProtocolTestTnpa
    {
        public int id { get; set; }
        public System.Guid protocolid { get; set; }
        public string dens { get; set; }
        public string water { get; set; }
        public string salt { get; set; }
        public string mechan { get; set; }
        public string sulphur { get; set; }
        public string vaporpres { get; set; }
        public string fraction { get; set; }
        public string paraffin { get; set; }
        public string hydrogen { get; set; }
        public string mercaptan { get; set; }
        public string organic { get; set; }
        public Nullable<bool> visc { get; set; }
        public string densAstm { get; set; }
    }
}
