//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TankService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProtocolTest
    {
        public int id { get; set; }
        public System.Guid protocolid { get; set; }
        public bool dens { get; set; }
        public bool water { get; set; }
        public bool salt { get; set; }
        public bool mechan { get; set; }
        public bool sulphur { get; set; }
        public bool vaporpres { get; set; }
        public bool fraction { get; set; }
        public bool paraffin { get; set; }
        public bool hydrogen { get; set; }
        public bool mercaptan { get; set; }
        public bool organic { get; set; }
        public bool visc { get; set; }
        public bool densAstm { get; set; }
    }
}
