//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TankService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class qpass_tank
    {
        public System.Guid id { get; set; }
        public System.DateTime dt { get; set; }
        public System.DateTime dtwrite { get; set; }
        public Nullable<System.DateTime> dtclose { get; set; }
        public string levelsclose { get; set; }
        public Nullable<int> tank { get; set; }
        public string number { get; set; }
        public Nullable<double> densar { get; set; }
        public Nullable<double> tempar { get; set; }
        public Nullable<double> pres { get; set; }
        public Nullable<double> temp { get; set; }
        public Nullable<double> dens { get; set; }
        public Nullable<double> dens20 { get; set; }
        public Nullable<double> dens15 { get; set; }
        public Nullable<double> water { get; set; }
        public Nullable<double> saltmg { get; set; }
        public Nullable<double> saltprc { get; set; }
        public Nullable<double> mechan { get; set; }
        public Nullable<double> sulphur { get; set; }
        public Nullable<double> visc { get; set; }
        public Nullable<double> fr200 { get; set; }
        public Nullable<double> fr300 { get; set; }
        public Nullable<double> fr350 { get; set; }
        public Nullable<double> vaporpres { get; set; }
        public Nullable<double> paraffin { get; set; }
        public Nullable<double> hydrogen { get; set; }
        public Nullable<double> mercaptan { get; set; }
        public Nullable<double> organic { get; set; }
        public string mercaptan_str { get; set; }
        public string organic_str { get; set; }
        public string designpet { get; set; }
        public System.Guid operatorid { get; set; }
        public string user { get; set; }
    }
}
