//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TankService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResursiNefti
    {
        public int id { get; set; }
        public Nullable<int> idFilial { get; set; }
        public string Naimenovanie { get; set; }
        public Nullable<decimal> VNefti { get; set; }
    
        public virtual filials filials { get; set; }
    }
}
