//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TankService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SampleLocation
    {
        public int id { get; set; }
        public int filialid { get; set; }
        public int sourceid { get; set; }
        public string name { get; set; }
        public Nullable<int> tankid { get; set; }
        public bool enable { get; set; }
        public Nullable<int> directionid { get; set; }
    }
}
