//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TankService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sikn495masscounter
    {
        public long id { get; set; }
        public int line { get; set; }
        public System.DateTime dtwrite { get; set; }
        public System.DateTime dt { get; set; }
        public double value { get; set; }
        public Nullable<byte> state { get; set; }
    }
}
