//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TankService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sut
    {
        public Nullable<System.Guid> id { get; set; }
        public int unitid { get; set; }
        public System.DateTime fordate { get; set; }
        public System.DateTime dtwrite { get; set; }
        public Nullable<double> t { get; set; }
        public Nullable<double> pres { get; set; }
        public Nullable<double> dens { get; set; }
        public Nullable<double> dens20 { get; set; }
        public Nullable<double> dens15 { get; set; }
        public Nullable<double> water { get; set; }
        public Nullable<int> mass { get; set; }
        public Nullable<int> volume { get; set; }
    }
}
