//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TankService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TagCorrespondence
    {
        public int ID { get; set; }
        public string lev { get; set; }
        public string temp { get; set; }
        public int FilialID { get; set; }
        public int TankID { get; set; }
        public Nullable<int> Enable { get; set; }
        public string Primechanie { get; set; }
    }
}
