//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TankService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tanktags
    {
        public int id { get; set; }
        public string level { get; set; }
        public string t { get; set; }
        public Nullable<int> filialid { get; set; }
        public Nullable<int> tankid { get; set; }
        public Nullable<short> typeid { get; set; }
        public byte enable { get; set; }
    }
}
