//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TankService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestTnpaNew
    {
        public int id { get; set; }
        public Nullable<int> testtypeid { get; set; }
        public string name { get; set; }
        public string comment { get; set; }
        public bool @default { get; set; }
    }
}
