//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TankService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestDensTnpa
    {
        public int id { get; set; }
        public string densroom { get; set; }
        public string densreal { get; set; }
        public string dens20 { get; set; }
        public string dens15 { get; set; }
    }
}
