//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TankService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tool
    {
        public System.Guid id { get; set; }
        public int filialid { get; set; }
        public string name { get; set; }
        public string sernum { get; set; }
        public string regnum { get; set; }
        public Nullable<short> year { get; set; }
        public Nullable<System.DateTime> checkdate { get; set; }
        public bool actual { get; set; }
        public string fullname { get; set; }
        public string comment { get; set; }
    }
}
