//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TankService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trl_tank
    {
        public int ID { get; set; }
        public int TypeID { get; set; }
        public string Name { get; set; }
        public Nullable<double> MinDopLevel { get; set; }
        public Nullable<double> MinDopVol { get; set; }
        public Nullable<double> MaxVolume { get; set; }
        public Nullable<double> grdTemper { get; set; }
        public Nullable<double> volCoef { get; set; }
        public Nullable<double> WorkVolume { get; set; }
        public Nullable<int> TankID { get; set; }
        public Nullable<int> FilialID { get; set; }
    
        public virtual trl_tanktype trl_tanktype { get; set; }
    }
}
