//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TankService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class twohours
    {
        public int id { get; set; }
        public int unitid { get; set; }
        public System.DateTime dt { get; set; }
        public System.DateTime dtwrite { get; set; }
        public int h2 { get; set; }
        public int h4 { get; set; }
        public int h6 { get; set; }
        public int h8 { get; set; }
        public int h10 { get; set; }
        public int h12 { get; set; }
        public int h14 { get; set; }
        public int h16 { get; set; }
        public int h18 { get; set; }
        public int h20 { get; set; }
        public int h22 { get; set; }
        public int h24 { get; set; }
        public Nullable<double> t { get; set; }
        public Nullable<double> p { get; set; }
    }
}
