//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TankService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users2old
    {
        public int id { get; set; }
        public int personid { get; set; }
        public int roleid { get; set; }
        public string login { get; set; }
        public byte[] pass { get; set; }
        public string email { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
