//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TankService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class valveinfo_view
    {
        public long id { get; set; }
        public System.DateTime dt { get; set; }
        public string alias { get; set; }
        public byte value { get; set; }
        public string tag { get; set; }
    }
}
